# Generated by Django 4.0.3 on 2022-03-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_location',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
