# Generated by Django 4.0.3 on 2022-03-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_class',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_location',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
