# Generated by Django 4.0.3 on 2022-03-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_item_class_alter_item_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
