# Generated by Django 4.0.3 on 2022-03-30 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_item_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_qty', models.PositiveIntegerField()),
                ('item_complete', models.BooleanField(default=False)),
                ('added_on', models.DateField(auto_now=True)),
                ('list_num', models.PositiveIntegerField(blank=True)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('shopper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
