# Generated by Django 4.0.3 on 2022-03-30 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shopping_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_list',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.item'),
        ),
    ]
