# Generated by Django 4.0.3 on 2022-03-30 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_shopping_list_item_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping_List',
            new_name='ShoppingList',
        ),
    ]
