# Generated by Django 4.0.3 on 2022-03-30 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_shopping_list_shoppinglist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='item_name',
            new_name='item_num',
        ),
    ]
