# Generated by Django 4.0.3 on 2022-04-02 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_item_name_shoppinglist_item_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='item_num',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='item',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='api.item'),
            preserve_default=False,
        ),
    ]
