# Generated by Django 4.0.3 on 2022-04-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_shoppinglist_item_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='item_qty',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
