# Generated by Django 4.0.3 on 2022-04-03 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_shoppinglist_item_shoppinglist_item_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='item_num',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='item',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shopping_lists', to='api.item'),
            preserve_default=False,
        ),
    ]
