# Generated by Django 4.0.3 on 2022-04-03 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_shoppinglist_item_num_shoppinglist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='item',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='item_num',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.DO_NOTHING, to='api.item'),
            preserve_default=False,
        ),
    ]
